# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x64)
  Chip8_Interpreter_config = debug_x64
  raylib_config = debug_x64
  tests_config = debug_x64

else ifeq ($(config),debug_x86)
  Chip8_Interpreter_config = debug_x86
  raylib_config = debug_x86
  tests_config = debug_x86

else ifeq ($(config),debug_arm64)
  Chip8_Interpreter_config = debug_arm64
  raylib_config = debug_arm64
  tests_config = debug_arm64

else ifeq ($(config),release_x64)
  Chip8_Interpreter_config = release_x64
  raylib_config = release_x64
  tests_config = release_x64

else ifeq ($(config),release_x86)
  Chip8_Interpreter_config = release_x86
  raylib_config = release_x86
  tests_config = release_x86

else ifeq ($(config),release_arm64)
  Chip8_Interpreter_config = release_arm64
  raylib_config = release_arm64
  tests_config = release_arm64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Chip8-Interpreter raylib tests

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Chip8-Interpreter: raylib
ifneq (,$(Chip8_Interpreter_config))
	@echo "==== Building Chip8-Interpreter ($(Chip8_Interpreter_config)) ===="
	@${MAKE} --no-print-directory -C build -f Chip8-Interpreter.make config=$(Chip8_Interpreter_config)
endif

raylib:
ifneq (,$(raylib_config))
	@echo "==== Building raylib ($(raylib_config)) ===="
	@${MAKE} --no-print-directory -C . -f raylib.make config=$(raylib_config)
endif

tests:
ifneq (,$(tests_config))
	@echo "==== Building tests ($(tests_config)) ===="
	@${MAKE} --no-print-directory -C build -f tests.make config=$(tests_config)
endif
	./bin/Debug/tests

run: raylib
ifneq (,$(Chip8_Interpreter_config))
	@echo "==== Building Chip8-Interpreter ($(Chip8_Interpreter_config)) ===="
	@${MAKE} --no-print-directory -C build -f Chip8-Interpreter.make config=$(Chip8_Interpreter_config)
endif
	./bin/Debug/Chip8-Interpreter

clean:
	@${MAKE} --no-print-directory -C build -f Chip8-Interpreter.make clean
	@${MAKE} --no-print-directory -C . -f raylib.make clean
	@${MAKE} --no-print-directory -C build -f tests.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x64"
	@echo "  debug_x86"
	@echo "  debug_arm64"
	@echo "  release_x64"
	@echo "  release_x86"
	@echo "  release_arm64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Chip8-Interpreter"
	@echo "   raylib"
	@echo "   tests"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"